.container * {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 14px;
}

.container {
  text-align: center;
  width: 325px;
  margin: 20px auto 10px;
  display: block;
  border-radius: 5px;
  box-sizing: border-box;
  color: #ffffff;

  .policies {
    p {
      color: black;
      font-size: 0.75em;
      span,
      a {
        font-size: 1.2em;
        font-weight: bold;
        cursor: pointer;
        color: #a6c307;
      }
    }
  }
  @media screen and (min-width: 992px) {
    width: 420px;
  }
}

.cardContainer {
  width: 100%;
  margin: 0 auto;
  border-radius: 6px;
  padding: 10px;
  background: rgb(2, 0, 60);
  text-align: left;
  box-sizing: border-box;

  aside {
    margin: 6px 0;
  }
}

.payuCardForm {
  background-color: #ffffff;
  padding: 5px;
  border-radius: 4px;
}

.cardDetails {
  clear: both;
  overflow: auto;
  .expiration {
    width: 50%;
    float: left;
    padding-right: 5%;
  }

  .cvv {
    width: 45%;
    float: left;
  }
}

.responseSuccess {
  color: #438f29;
}

.responseError {
  color: #990000;
}

.button {
  border: none;
  background: #438f29;
  padding: 8px 15px;
  margin: 10px auto;
  cursor: pointer;
}
